export type Locale = "en" | "el";

export const localeNames: Record<Locale, string> = {
  en: "English",
  el: "Ελληνικά",
};

const translations = {
  en: {
    // App
    appName: "My Little Story",
    appTagline: "Magical stories, made just for your child",

    // Form labels
    formChildName: "Child's Name",
    formChildNamePlaceholder: "e.g. Emma",
    formAge: "Age",
    formAgeSelect: "Select age",
    formAgeYears: "years old",
    formTheme: "Story Theme or Moral",
    formThemePlaceholder: "e.g. sharing is caring, being brave…",
    formCharacter: "Favorite Character",
    formCharacterPlaceholder: "e.g. a talking fox",
    formSetting: "Story Setting",
    formSettingPlaceholder: "e.g. an enchanted forest",
    formLength: "Story Length",
    formLengthShort: "Short (bedtime)",
    formLengthMedium: "Medium (read-along)",
    formFormat: "Format",
    formFormatStory: "Story",
    formFormatPoem: "Poem",
    formStoryLanguage: "Story Language",
    formGender: "Child's Gender",
    formGenderBoy: "👦 Boy",
    formGenderGirl: "👧 Girl",
    formMoreOptions: "More Options",
    formSubmit: "✨ Create Story",
    formSubmitting: "Creating…",

    // Theme suggestion chips
    sugKindness: "kindness",
    sugSharing: "sharing",
    sugBrave: "being brave",
    sugFriendship: "friendship",
    sugHonesty: "honesty",
    sugTrying: "trying new things",

    // Story page
    storyFor: "A story for",
    poemFor: "A poem for",
    newStory: "New Story",
    readAloud: "🔊 Read Aloud",
    stopReading: "⏹ Stop Reading",
    pauseReading: "⏸ Pause",
    resumeReading: "▶ Resume",
    createAnother: "✨ Create Another Story",
    theEnd: "~ The End ~",
    prev: "Prev",
    next: "Next",

    // Cover
    openBook: "📖  Open Book",
    writingStory: "Writing your story…",
    paintingCover: "🎨  Painting the cover…",

    // Loading screen
    creatingStory: "Creating a story for",
    creatingPoem: "Creating a poem for",
    openingBook: "Opening the book of imagination",

    // Error
    errorOops: "Oops!",
    errorBack: "Go Back",

    // Settings panel
    settingsTitle: "Settings",
    settingsLanguage: "App Language",
    settingsTheme: "Theme",
    settingsDark: "Dark",
    settingsLight: "Light",

    // Voice
    voiceTitle: "Read in Your Voice",
    voiceDescription: "Record yourself reading a short passage (at least 10 seconds) so the story can be read aloud in your voice.",
    voiceStart: "Start Recording",
    voiceStop: "Stop Recording",
    voiceKeepGoing: "Keep going — need at least 10 seconds…",
    voiceGoodToStop: "Good! You can stop whenever you're ready.",
    voiceProcessing: "Cloning your voice…",
    voiceReady: "Your voice is ready!",
    voiceRerecord: "Re-record",
    voiceMicError: "Could not access microphone. Please allow microphone access.",
    voiceTooShort: "Recording too short. Please record at least 10 seconds.",
    voiceReadAloud: "🔊 Read in My Voice",
    voiceLoading: "Preparing audio…",

    // Footer
    footer: "Stories generated by AI. Always review content before sharing with children.",
  },
  el: {
    // App
    appName: "Η Μικρή Ιστορία Μου",
    appTagline: "Μαγικές ιστορίες, φτιαγμένες για το παιδί σας",

    // Form labels
    formChildName: "Όνομα Παιδιού",
    formChildNamePlaceholder: "π.χ. Ελένη",
    formAge: "Ηλικία",
    formAgeSelect: "Επιλέξτε ηλικία",
    formAgeYears: "ετών",
    formTheme: "Θέμα ή Ηθικό Δίδαγμα",
    formThemePlaceholder: "π.χ. φιλία, θάρρος…",
    formCharacter: "Αγαπημένος Χαρακτήρας",
    formCharacterPlaceholder: "π.χ. μια αλεπού",
    formSetting: "Σκηνικό Ιστορίας",
    formSettingPlaceholder: "π.χ. μαγικό δάσος",
    formLength: "Μήκος Ιστορίας",
    formLengthShort: "Σύντομη (για ύπνο)",
    formLengthMedium: "Μεσαία (για ανάγνωση)",
    formFormat: "Μορφή",
    formFormatStory: "Ιστορία",
    formFormatPoem: "Ποίημα",
    formStoryLanguage: "Γλώσσα Ιστορίας",
    formGender: "Φύλο Παιδιού",
    formGenderBoy: "👦 Αγόρι",
    formGenderGirl: "👧 Κορίτσι",
    formMoreOptions: "Περισσότερες Επιλογές",
    formSubmit: "✨ Δημιουργία Ιστορίας",
    formSubmitting: "Δημιουργία…",

    // Theme suggestion chips
    sugKindness: "καλοσύνη",
    sugSharing: "μοίρασμα",
    sugBrave: "θάρρος",
    sugFriendship: "φιλία",
    sugHonesty: "ειλικρίνεια",
    sugTrying: "νέες εμπειρίες",

    // Story page
    storyFor: "Μια ιστορία για",
    poemFor: "Ένα ποίημα για",
    newStory: "Νέα Ιστορία",
    readAloud: "🔊 Ανάγνωση",
    stopReading: "⏹ Διακοπή",
    pauseReading: "⏸ Παύση",
    resumeReading: "▶ Συνέχεια",
    createAnother: "✨ Δημιουργία νέας ιστορίας",
    theEnd: "~ Τέλος ~",
    prev: "Προηγ.",
    next: "Επόμ.",

    // Cover
    openBook: "📖  Άνοιγμα Βιβλίου",
    writingStory: "Γράφω την ιστορία σας…",
    paintingCover: "🎨  Ζωγραφίζω το εξώφυλλο…",

    // Loading screen
    creatingStory: "Δημιουργία ιστορίας για",
    creatingPoem: "Δημιουργία ποιήματος για",
    openingBook: "Ανοίγοντας το βιβλίο της φαντασίας",

    // Error
    errorOops: "Ωχ!",
    errorBack: "Πίσω",

    // Settings panel
    settingsTitle: "Ρυθμίσεις",
    settingsLanguage: "Γλώσσα Εφαρμογής",
    settingsTheme: "Θέμα",
    settingsDark: "Σκοτεινό",
    settingsLight: "Φωτεινό",

    // Voice
    voiceTitle: "Διαβάστε με τη Φωνή σας",
    voiceDescription: "Ηχογραφήστε τον εαυτό σας (τουλάχιστον 10 δευτερόλεπτα) για να διαβαστεί η ιστορία με τη φωνή σας.",
    voiceStart: "Έναρξη Ηχογράφησης",
    voiceStop: "Διακοπή Ηχογράφησης",
    voiceKeepGoing: "Συνεχίστε — χρειάζονται τουλάχιστον 10 δευτερόλεπτα…",
    voiceGoodToStop: "Τέλεια! Μπορείτε να σταματήσετε.",
    voiceProcessing: "Κλωνοποίηση φωνής…",
    voiceReady: "Η φωνή σας είναι έτοιμη!",
    voiceRerecord: "Επανεγγραφή",
    voiceMicError: "Δεν ήταν δυνατή η πρόσβαση στο μικρόφωνο.",
    voiceTooShort: "Η ηχογράφηση είναι πολύ σύντομη. Ηχογραφήστε τουλάχιστον 10 δευτερόλεπτα.",
    voiceReadAloud: "🔊 Ανάγνωση με τη Φωνή μου",
    voiceLoading: "Προετοιμασία ήχου…",

    // Footer
    footer: "Ιστορίες από AI. Ελέγχετε πάντα το περιεχόμενο πριν το μοιραστείτε με παιδιά.",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

export function t(locale: Locale, key: TranslationKey): string {
  return translations[locale][key] ?? translations.en[key] ?? key;
}
