import { StoryGenerator } from "@/components/story-generator";

export default function Home() {
  return (
    <div className="flex flex-col flex-1 items-center bg-gradient-to-b from-violet-50 to-white min-h-screen">
      <header className="w-full py-10 text-center">
        <h1 className="text-4xl sm:text-5xl font-extrabold text-violet-800 tracking-tight">
          Small Stories
        </h1>
        <p className="mt-2 text-lg text-violet-600">
          Magical stories, just for your child
        </p>
      </header>

      <main className="flex-1 w-full max-w-2xl px-4 sm:px-6 pb-16">
        <StoryGenerator />
      </main>

      <footer className="w-full py-6 text-center text-sm text-gray-400">
        Stories generated by AI. Always review content before sharing with children.
      </footer>
    </div>
  );
}
